settings:
  username: "devtobi"
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 10
  readme_file: "./README.md"
  disabled_events: []
  date:
    timezone: "Europe/Berlin"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "actions@github.com"
  line_prefix: "{NUM}. "
