name: Update contributions Snake animation

on:
  schedule:
    - cron: '0 0 * * *' # Update every day at 00:00
  workflow_dispatch:
jobs:
  generate:
    name: Update contributions Snake animation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Generate GitHub contributions Snake animations
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit to snake branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: snake
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}